groups:
  - name: SSL_Expiry
    rules:
      - alert: BlackboxSslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 7*24*3600
        for: 0m
        keep_firing_for: 5s
        labels:
          severity: warning
          service: sslexpiry
        annotations:
          summary: Certificate for {{ $labels.instance }} is about to expire
          description: "The certificate for {{ $labels.instance }} is about to expire in
            less than 7 days."
