volumes:
  prometheus-data:
  alertmanager-data:

services:

  prometheus:
    image: prom/prometheus:v3
    container_name: status_prometheus
    ports:
      - '9090:9090'
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules/rules.yml:/etc/prometheus/rules/rules.yml
      - prometheus-data:/prometheus
    command:
      - '--web.enable-lifecycle' # To enable /-/reload, to restart prometheus with new config
      - '--config.file=/etc/prometheus/prometheus.yml'

  alertmanager:
    image: prom/alertmanager:v0.31.1
    container_name: status_alertmanager
    restart: unless-stopped
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana
    container_name: status_grafana
    restart: always
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards
    ports:
      - "3030:3000"

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.28.0
    container_name: status_blackbox_exporter
    ports:
      - '9115:9115'
    restart: unless-stopped
    volumes:
      - ./blackbox:/config
    command:
      - '--config.file=/config/blackbox.yml'

  node_exporter:
    image: prom/node-exporter:v1.10.2
    container_name: status_node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100