# https://github.com/epfl-si/cluster.k8s.testserver/issues
# quay-its.epfl.ch/svc0041/testserver
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: testserver
  namespace: svc0041p-status-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testserver
  template:
    metadata:
      labels:
        app: testserver
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: svc0041-pull-secret
      containers:
      - name: testserver
        image: "quay-its.epfl.ch/svc0041/testserver:latest"
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 50Mi
        ports:
        - containerPort: 3000
          protocol: TCP
        imagePullPolicy: Always
        terminationMessagePolicy: File

---
kind: Service
apiVersion: v1
metadata:
  name: testserver-service
  namespace: svc0041p-status-prod
  labels:
    app: testserver
spec:
  selector:
    app: testserver
  ports:
    - name: testserver-http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: testserver-route
  namespace: svc0041p-status-prod
  labels:
    route: public-cf
spec:
  host: status-testserver.fsd.epfl.ch
  to:
    kind: Service
    name: testserver-service
    weight: 100
  port:
    targetPort: testserver-http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
