scrape_configs:
  - job_name: blackbox
    metrics_path: /probe
    params:
      module:
        - http_2xx
        - icmp
    static_configs:
      - targets:
          - https://go.epfl.ch
          - https://ticketshop.epfl.ch
          - https://go.epfl.ch/nbo
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: status_blackbox_exporter:9115
